# -*- coding: utf-8 -*-
"""Dustin Nghiem - Beats by Dre Consumer Insights -  Capstone Project Template

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ua6wnDFKXUWDY2Vorzc8RmhHmD1epK_2

# Capstone Project: Consumer Insights Data Analytics Externship of Beats by Dre

## 1. Title Page
**Project Title:** Consumer Insights Data Analytics Externship of Beats by Dre  
**Student Name:** Dustin Nghiem

**Date:** 9/2/2024

## 2. Table of Contents
1. Introduction
2. Data Description
3. Exploratory Data Analysis (EDA)
4. Sentiment Analysis
5. AI-Generated Insights
6. Comparative Analysis
7. Strategic Recommendations
8. Conclusion
9. References

## 3. Introduction

### 3.1 Project Overview
The purpose of this project is to analyze consumer sentiment towards Beats by Dre products by leveraging data science techniques. As part of my role as a Consumer Insights Data Analytics Extern at Beats by Dre, this project is focused on gathering and analyzing data from various sources, such as Amazon reviews, to uncover insights that can inform product improvements, marketing strategies, and overall business decisions.

### 3.2 Background

Beats by Dre, officially known as Beats Electronics LLC, is a leading audio brand that was founded in 2006 by music producer Dr. Dre and record company executive Jimmy Iovine. The company specializes in producing high-quality audio products, including headphones, earphones, and speakers. Beats by Dre quickly gained popularity due to its stylish design, celebrity endorsements, and strong marketing campaigns.

In 2014, Beats Electronics was acquired by Apple Inc. for $3 billion, making it one of Apple's largest acquisitions. This acquisition allowed Apple to integrate Beats' audio technology into its own products, as well as benefit from Beats' brand appeal and market share in the audio industry. Beats by Dre remains a significant player in the market, known for its premium pricing, distinctive design, and high-profile collaborations with artists and athletes.

Importance of Consumer Sentiment Analysis in the Tech Industry
Consumer sentiment analysis is a crucial tool for companies in the tech industry for several reasons:

Understanding Customer Preferences: By analyzing consumer sentiment, companies can gain insights into what customers like and dislike about their products. This helps in refining product features and making informed decisions about product development.

Brand Management: Consumer sentiment analysis helps in monitoring the overall perception of the brand. It enables companies to identify potential issues that could harm their reputation and address them proactively.

Competitive Advantage: Understanding how consumers feel about competitors' products can provide valuable insights. Companies can identify gaps in the market and develop strategies to gain an edge over their competitors.

Product Improvement: Feedback from consumers can highlight common problems or desired features, guiding companies to improve their products accordingly. This leads to better customer satisfaction and loyalty.

Marketing Strategies: Analyzing consumer sentiment helps in crafting more effective marketing messages that resonate with the target audience. It allows companies to tap into the emotional and psychological drivers behind purchasing decisions.

Crisis Management: In the event of a product failure or negative publicity, sentiment analysis can help companies gauge the impact and respond appropriately. Quick and effective responses can mitigate damage and restore consumer trust.

Trend Identification: Keeping track of consumer sentiment can reveal emerging trends and shifts in consumer behavior. This information is vital for staying ahead of the curve and adapting to changing market conditions.

For tech companies like Beats by Dre, where brand image and consumer perception play a significant role in market success, sentiment analysis is an invaluable tool for maintaining a competitive edge and ensuring long-term customer satisfaction.

## 4. Data Description

### 4.1 Data Sources
Describe the sources of your data (e.g., Amazon reviews).

Sources: Amazon Reviews

### 4.2 Data Collection
Explain the data gathering process, including any challenges faced and how they were overcome.

The first step in gathering data for consumer sentiment analysis is to identify reliable sources of customer reviews and feedback. For this project, we used Amazon Reviews for all the products

To collect reviews, web scraping tools and scripts are used. These tools can automate the extraction of large volumes of review data from selected websites.

One significant challenge faced during data collection is the limitation on the number of reviews that can be scraped from third-party review aggregators. For instance, some tools may only allow scraping up to 100 reviews per product. This limitation can result in an insufficient dataset, which may not provide a comprehensive understanding of consumer sentiment.

Solution: Expanding the Product Range
To overcome the challenge of limited reviews, the solution involves expanding the range of products being analyzed. Here’s how this approach was implemented.

Identifying Similar Products: Instead of focusing solely on the Beats Pill, the data collection process was extended to include other similar portable speakers. This could include products from competitors such as JBL, Bose, and Sony. By combining reviews from multiple similar products, a more robust dataset was created. This larger dataset provided a better foundation for sentiment analysis, ensuring more accurate and reliable insights.

### 4.3 Data Cleaning
Outline the steps taken to clean and preprocess the data, highlighting any significant decisions made during this process.

Load the data below and process cleaning here.

Once the data is collected, it is often necessary to clean and preprocess it to ensure accuracy and usability. This involves removing duplicates, correcting errors, and standardizing the format of the reviews.

With the cleaned data, sentiment analysis algorithms can be applied to determine the overall sentiment (positive, negative, or neutral) of the reviews.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from wordcloud import WordCloud


df = pd.read_csv('/content/Final_Cleaned_Data_(2024) (1).csv')
df

"""## 5. Exploratory Data Analysis (EDA)

### 5.1 Data Overview
Provide a summary of the dataset, including key statistics (mean, median, mode, standard deviation, etc.).

"""

mean_rating = df['Stars'].mean()
median_rating = df['Stars'].median()
mode_rating = df['Stars'].mode()[0]
variance_rating = df['Stars'].var()
std_rating = df['Stars'].std()
quantiles_rating = df['Stars'].quantile([0.25, 0.5, 0.75])

print("Mean Rating:", mean_rating)
print("Median Rating:", median_rating)
print("Mode Rating:", mode_rating)
print("Variance Rating:", variance_rating)
print("Standard Deviation Rating:", std_rating)
print("Quantiles Rating:", quantiles_rating)


df.describe()

"""### 5.2 Visualizations
Include relevant visualizations (histograms, box plots, scatter plots, etc.) and explain what each visualization reveals about the data.
"""

sta_plt = sns.countplot(x='Stars', data=df)
sta_plt.set_title('Distribution of Stars')
sta_plt.set_xlabel('Stars')
sta_plt.set_ylabel('Count')
plt.show()

"""The plot above shows the distribution of the ratings, and it clearly shows that almost 800 of the products are rated 5 stars on Amazon. The difference from 5 Star and 4 Star is strikingly huge."""

plt.figure(figsize=(8, 6))
sns.boxplot(x='Stars', y='Product', data=df)
plt.title('Distribution of Ratings')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

"""This boxplot graph shows the rating distribution for each of the 13 products in the dataset. Specifically looking at the two Beats Products, both are highly rated with outliers from 4 star and below.

It makes sense for the Beats Pill that the outliers are 4 and below since there were barely any reviews done on this product.
"""

all_reviews = ' '.join(df['Description'].dropna())

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_reviews)

plt.figure(figsize=(15, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Description Text')
plt.show()

all_titles = ' '.join(df['Title'].dropna())

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_titles)

plt.figure(figsize=(15, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Title Text')
plt.show()

from collections import Counter


reviews = list(df['Description'].iloc[0:1037])

processed_reviews = [' '.join(word.lower() for word in review.split() if word.isalnum()) for review in reviews]

word_count = Counter()
for review in processed_reviews:
    word_count.update(review.split())

print("Word Frequency Count:")
for word, count in word_count.items():
    print(f"{word}: {count}")

"""### 5.3 Descriptive Statistics


Customers commonly use words like "best," "good," "sound," "quality," "great," "amazing," "awesome," "excellent," "perfect," "loud," and "powerful" to describe the positive aspects of their speakers.
They also use "portable," "small," "light," and "easy" to highlight the speakers' convenience and portability.
When it comes to sound quality, terms like "clear," "crisp," "bass," "volume," and "stereo" are frequently used.
Other words that appear often include "battery," "life," "Bluetooth," "waterproof," "durable," and "price."
"""



"""## 6. Sentiment Analysis

### 6.1 Methodology

For this project, we will being using a library called TextBlob. TextBlob is a popular Python library for processing textual data. It provides a simple API for common natural language processing tasks, such as part-of-speech tagging, noun phrase extraction, sentiment analysis, classification, translation, and more. For sentiment analysis, TextBlob uses a combination of rule-based and machine learning algorithms to assign a polarity (positive, negative, or neutral) to the text.

Key Features of TextBlob for Sentiment Analysis

Polarity: A float within the range [-1.0, 1.0] where -1 indicates negative sentiment and 1 indicates positive sentiment.

Subjectivity: A float within the range [0.0, 1.0] where 0 is very objective and 1 is very subjective.
"""

from textblob import TextBlob

def sentiment_analysis_summary(df, text_col, start_row=None, end_row=None):
    positive, negative, neutral = 0, 0, 0


    if start_row is not None and end_row is not None:
        for i in range(start_row, end_row):
            text = df.iloc[i][text_col]
            analysis = TextBlob(text)
            polarity = analysis.sentiment.polarity

            if polarity > 0:
                positive += 1
            elif polarity < 0:
                negative += 1
            else:
                neutral += 1
    else:
        for text in df[text_col]:
            analysis = TextBlob(text)
            polarity = analysis.sentiment.polarity

            if polarity > 0:
                positive += 1
            elif polarity < 0:
                negative += 1
            else:
                neutral += 1

    return {
        'positive': positive,
        'negative': negative,
        'neutral': neutral
    }

"""### 6.2 Results
Present the sentiment analysis results, including visualizations of sentiment distribution, and discuss the overall sentiment towards Beats by Dre products.

"""

sentiment_analysis_summary(df, "Description")

sentiment_counts = sentiment_analysis_summary(df, 'Description')

labels = ['Positive', 'Negative', 'Neutral']
counts = [sentiment_counts['positive'], sentiment_counts['negative'], sentiment_counts['neutral']]

plt.bar(labels, counts)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Overall)')
plt.show()

# only Beats Pill and Beats Plus
sentiment_counts2 = sentiment_analysis_summary(df, 'Description', 90, 222)

labels2 = ['Positive', 'Negative', 'Neutral']
counts2 = [sentiment_counts2['positive'], sentiment_counts2['negative'], sentiment_counts2['neutral']]

plt.bar(labels2, counts2)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Beats Pill and Beats Pill Plus)')
plt.show()

"""By applying sentiment analysis and with the visuals above, it is safe to say that the overall sentiment of these products is positive. To be more specific, by only looking at the Beats Products, the sentiment is largely positive with very little negative and neutral sentiment.

## 7. AI-Generated Insights

### 7.1 Using Gemini AI

For this project, we used Gemini AI to extract insights from the data, specifically the reviews from the customers. Specifically, Gemini AI allowed us to understand what the customers like and dislike about products, which in our case are speakers.
"""

import os

import google.generativeai as genai

genai.configure(api_key="AIzaSyBrBbndVgxfCKXEsQ1atCuee3esmTUJtss")

generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 64,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-1.5-flash",
  generation_config=generation_config,
  # safety_settings = Adjust safety settings
  # See https://ai.google.dev/gemini-api/docs/safety-settings
)

import pandas as pd
import google.generativeai as genai

# Load your dataset
df = pd.read_csv('/content/Final_Cleaned_Data_(2024) (1).csv')

# Replace 'your_api_key' with the actual API key
api_key = "AIzaSyBrBbndVgxfCKXEsQ1atCuee3esmTUJtss"

# Function to analyze reviews using Gemini AI
def analyze_reviews(reviews, api_key,prompt_message):
    genai.configure(api_key=api_key)

    model = genai.GenerativeModel(
        model_name="gemini-1.5-flash",
        generation_config={
            "temperature": 1,
            "top_p": 0.95,
            "top_k": 64,
            "max_output_tokens": 8192,
            "response_mime_type": "text/plain",
        },
    )

    chat_session = model.start_chat(history=[])

    prompt = prompt_message + "\n\n".join(reviews)
    response = chat_session.send_message(prompt)
    return response.text

# Select a subset of reviews (Beats Pill ONLY)

reviews_column_name = 'Description'
reviews = df[reviews_column_name].iloc[90:122].tolist()

"""### 7.2 Key Insights


"""

prompt_message = "Analyze the following reviews and summarize the key insights:"
insights = analyze_reviews(reviews, api_key, prompt_message)
print(insights)

prompt_message2 = "Identify different customer segments based on the following reviews:"
insights2 = analyze_reviews(reviews, api_key, prompt_message2)
print(insights2)

prompt_message3 = "What are the unique selling points of the product according to the reviews?)"
insights3 = analyze_reviews(reviews, api_key, prompt_message3)
print(insights3)

"""### 7.3 Interpretation

By specifically looking into Beats products, the use of Gemini AI can give any synopsis for any prompt we put in. In this case, we used 3 prompts to get some feedback about what the customers think about the product. Because we can also filter which products we can ask Gemini to specifically talk about, we can ask AI to talk about the insights specifically about the Beats products.

By asking questions such as the positives and negatives of Beats products and what the unique selling points are, the company can gain insight that can be considered into current and future products.

## 8. Comparative Analysis

### 8.1 Competitor Overview


Bose: Known for its industry-leading noise cancellation technology and high-end audio quality, Bose targets premium-conscious consumers.

Beats: Owned by Apple, Beats focuses on style, celebrity endorsements, and a strong presence in the urban market.

Sonos: A pioneer in multi-room audio systems, Sonos caters to tech-savvy consumers seeking high-quality, connected audio experiences.

Marshall: Leveraging its iconic rock-and-roll heritage, Marshall offers a blend of retro aesthetics and modern audio technology for a niche audience.
Value-Oriented Brands

JBL: Under Harman International, JBL offers a wide range of products across various price points, emphasizing strong bass and affordability.

Anker: A rapidly growing brand known for its portable power banks, Anker has expanded into audio with a focus on value and feature-rich products.
Emerging and Budget-Oriented Brands

Treblab: This brand competes in the budget segment, offering affordable
wireless headphones and speakers with basic features.

Vanzon: Another budget-oriented player, Vanzon targets price-sensitive consumers with a range of audio products.

### 8.2 Comparison of Sentiments
Compare the sentiment analysis results of Beats by Dre with its competitors using visualizations to highlight differences and similarities.
"""

#Anker products
sentiment_counts3 = sentiment_analysis_summary(df, 'Description', 0, 89)

labels3 = ['Positive', 'Negative', 'Neutral']
counts3 = [sentiment_counts3['positive'], sentiment_counts3['negative'], sentiment_counts3['neutral']]

plt.bar(labels3, counts3)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Anker)')
plt.show()

#beats products
sentiment_counts4 = sentiment_analysis_summary(df, 'Description', 90, 222)

labels4 = ['Positive', 'Negative', 'Neutral']
counts4 = [sentiment_counts4['positive'], sentiment_counts4['negative'], sentiment_counts4['neutral']]

plt.bar(labels4, counts4)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Beats)')
plt.show()

#Bose products
sentiment_counts5 = sentiment_analysis_summary(df, 'Description', 223, 322)

labels5 = ['Positive', 'Negative', 'Neutral']
counts5 = [sentiment_counts5['positive'], sentiment_counts5['negative'], sentiment_counts5['neutral']]

plt.bar(labels5, counts5)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Bose)')
plt.show()

#Jbl Products
sentiment_counts6 = sentiment_analysis_summary(df, 'Description', 323, 712)

labels6 = ['Positive', 'Negative', 'Neutral']
counts6 = [sentiment_counts6['positive'], sentiment_counts6['negative'], sentiment_counts6['neutral']]

plt.bar(labels6, counts6)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (JBL)')
plt.show()

#Sonos Products
sentiment_counts7 = sentiment_analysis_summary(df, 'Description', 713, 770)

labels7 = ['Positive', 'Negative', 'Neutral']
counts7 = [sentiment_counts7['positive'], sentiment_counts7['negative'], sentiment_counts7['neutral']]

plt.bar(labels7, counts7)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Sonos)')
plt.show()

#Treblab Products
sentiment_counts8 = sentiment_analysis_summary(df, 'Description', 771, 860)

labels8 = ['Positive', 'Negative', 'Neutral']
counts8 = [sentiment_counts8['positive'], sentiment_counts8['negative'], sentiment_counts8['neutral']]

plt.bar(labels8, counts8)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (TREBLAB)')
plt.show()

#Vanzon Product
sentiment_counts9 = sentiment_analysis_summary(df, 'Description', 861, 960)

labels9 = ['Positive', 'Negative', 'Neutral']
counts9 = [sentiment_counts9['positive'], sentiment_counts9['negative'], sentiment_counts9['neutral']]

plt.bar(labels9, counts9)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Vanzon)')
plt.show()

#Marshall Product
sentiment_counts10 = sentiment_analysis_summary(df, 'Description', 961, 1050)

labels10 = ['Positive', 'Negative', 'Neutral']
counts10 = [sentiment_counts10['positive'], sentiment_counts10['negative'], sentiment_counts10['neutral']]

plt.bar(labels10, counts10)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (Marshall)')
plt.show()

"""### 8.3 SWOT Analysis
Conduct a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for Beats by Dre based on the comparative data.
"""

prompt_message4 = "Conduct a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for Beats by Dre based on the comparative data."
insights4 = analyze_reviews(reviews, api_key, prompt_message4)
print(insights3)

"""## 9. Strategic Recommendations

### 9.1 Product Improvements

Product Improvements:


Based on the analysis of the Beats Pill+ (2024), here are some specific product improvements that could enhance its overall user experience:

1. Balanced Sound Profile:
Improvement: Introduce a feature that allows users to customize the sound profile, such as an equalizer setting in the companion app or on the device itself.
Benefit: This would enable users to adjust the bass and other sound frequencies according to their preferences, making the speaker more versatile for different types of music and listening environments.
2. Enhanced Button Controls:
Improvement: Add a dedicated power button and more intuitive physical controls, including separate buttons for volume, play/pause, and track navigation.
Benefit: Simplifying the control interface would improve user convenience and reduce frustration, especially during active use like outdoor activities.
3. Stereo Sound Option:
Improvement: Enable stereo sound by allowing two Beats Pill+ speakers to be paired together for a true left and right channel experience.
Benefit: This would appeal to audiophiles and users who value a broader soundstage, enhancing the speaker's appeal in more sophisticated listening setups.
4. Improved High-Volume Performance:
Improvement: Enhance the internal components or software to reduce distortion and muddiness at high volumes.
Benefit: Maintaining sound clarity at higher volumes would ensure that the speaker performs well in loud environments, such as parties or outdoor gatherings.
5. Dust-Resistant Material:
Improvement: Use a different material for the speaker casing or apply a coating that repels dust and hair.
Benefit: Reducing the tendency to attract dust would lower the need for frequent cleaning, keeping the speaker looking clean and new with minimal effort.
6. Expand Compatibility Beyond Apple Devices:
Improvement: Improve the ease of pairing and integration with non-Apple devices, such as Android smartphones and other Bluetooth-enabled gadgets.
Benefit: Broadening compatibility would increase the product's appeal to a wider audience, not just Apple users.

### 9.2 Marketing Strategies

Marketing Strategies:

Target Specific Music Genres: Leverage Beats' strong bass performance by focusing marketing campaigns on music genres that prioritize bass (e.g., hip-hop, electronic dance music, bass-heavy rock).

Showcase Sound Quality in Engaging Ways:
Music Collaborations: Partner with popular artists to create exclusive content or playlists featuring the Pill.
Virtual Listening Experiences: Use immersive audio demonstrations or VR/AR experiences to highlight the Pill's sound quality.

Highlight Design and Portability:
Lifestyle Photography: Feature the Pill in stylish and adventurous settings to emphasize its portability and appeal.

Influencer Marketing: Collaborate with fashion, travel, and music influencers to promote the Pill's design and versatility.

Address Competitor Comparisons:
Direct Comparisons: Create marketing materials that directly compare the Pill's features and sound quality against competitors.

Feature Head-to-Head Tests: Conduct independent sound tests or user reviews to showcase the Pill's superiority in key areas.

### 9.3 Future Research

Future Research and Data Collection:

User Experience Feedback: Conduct more in-depth user surveys and reviews to gather detailed feedback on the Pill's overall experience, including:

Specific Use Cases: Identify how users primarily use the Pill (e.g., at home, outdoors, for parties) to tailor improvements.
Sound Quality Preferences: Gather user preferences regarding bass levels, EQ, and overall sound signature.

Market Research: Conduct ongoing market research to:
Identify Emerging Trends: Track changes in consumer preferences regarding portable speakers and audio technology.
Monitor Competitor Activities: Stay informed about competitor product launches, features, and marketing strategies.

## 10. Conclusion

Key Findings:

Sound Quality: The Beats Pill is generally praised for its sound quality, particularly the powerful bass. However, some reviewers find the bass to be overwhelming and prefer a more balanced sound profile.
Portability: The speaker's compact size and lightweight design make it highly portable, appealing to users who frequently take their speaker on the go.
Additional Features: The built-in microphone, portable power bank function, and water/dust resistance are valued by many users, especially those who seek a multi-functional speaker.
Apple Integration: Seamless integration with Apple devices is a significant advantage for Apple users, but it may limit the appeal to non-Apple users.
Design: The iconic pill-shaped design is well-received, but some users find the silicone material to be a dust magnet.
Implications:

Product Improvement: To further enhance the Beats Pill, Beats by Dre could focus on improving the sound profile customization options, enhancing button controls, enabling stereo sound, improving high-volume performance, and using a more dust-resistant material.
Target Market: The speaker's strengths in sound quality, portability, and additional features make it appealing to a wide range of consumers, including audiophiles, portability seekers, bass lovers, multi-functional users, and budget-conscious consumers.
Marketing Strategy: Beats by Dre could emphasize the speaker's portability, powerful sound, and seamless integration with Apple devices in their marketing campaigns. They could also highlight the speaker's versatility and additional features to appeal to a wider audience.
Competitive Landscape: To maintain its position in the competitive portable speaker market, Beats by Dre should continue to innovate and offer unique features that differentiate the Beats Pill from its competitors.
Overall Project Contribution:

This analysis has provided valuable insights into consumer sentiment for the Beats Pill. By identifying the speaker's strengths and weaknesses, as well as the preferences of different customer segments, this project has contributed to a better understanding of the factors that drive consumer choice in the portable speaker market. These findings can inform future product development, marketing strategies, and competitive analysis for Beats by Dre.

## 11. References
List all the sources, tools, and references used in the project.

Oxylabs

Amazon

Google Colab

Google Gemini AI
"""